name: Build Fungal RefSeq Database

on:
  workflow_dispatch:
    inputs:
      refseq_version:
        description: 'A version tag for this database build (e.g., 2025.06)'
        required: true
        default: '2025.06'

jobs:
  # --------------------------------------------------------------------------
  # JOB 1: Get the list of all fungal genomes from NCBI
  # --------------------------------------------------------------------------
  list_genomes:
    runs-on: ubuntu-latest
    outputs:
      genome_count: ${{ steps.check_size.outputs.count }}
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Download NCBI Datasets Tool
        run: |
          wget -q https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/datasets
          chmod +x datasets

      - name: Get Fungal Genome List
        run: |
          export PATH=$(pwd):$PATH
          ./datasets summary genome taxon 4751 --reference --as-json-lines | \
          jq -r '[.accession, .organism.organism_name] | @tsv' > ids.tsv

      - name: Check list size
        id: check_size
        run: |
          count=$(wc -l < ids.tsv)
          echo "Found ${count} fungal genomes."
          echo "count=${count}" >> $GITHUB_OUTPUT

      - name: Split id list for parallel jobs
        run: |
          # Split into 10 chunks for the matrix
          split -n l/10 ids.tsv -d --additional-suffix=.tsv x

      - name: Upload list chunks for next job
        uses: actions/upload-artifact@v4
        with:
          name: genome-chunks
          path: x*.tsv
          overwrite: true

  # --------------------------------------------------------------------------
  # JOB 2: Create sketches for each chunk in parallel (Final Robust Version)
  # --------------------------------------------------------------------------
  create_sketches:
    needs: list_genomes
    runs-on: ubuntu-latest
    # Increase the timeout as this job can be long
    timeout-minutes: 720 # 12 hours
    strategy:
      # Run jobs in parallel, but don't cancel others if one fails
      fail-fast: false
      matrix:
        chunk: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    steps:
      - name: Download Tools
        run: |
          wget -q https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/datasets
          chmod +x datasets
          wget -q https://github.com/marbl/Mash/releases/download/v2.3/mash-Linux64-v2.3.tar
          tar -xvf mash-Linux64-v2.3.tar && mv mash-Linux64-v2.3/mash .

      - name: Download genome chunk artifact
        uses: actions/download-artifact@v4
        with:
          name: genome-chunks
      
      - name: Download and Unzip All Genomes in Chunk
        run: |
          export PATH=$(pwd):$PATH
          INPUT_FILE=$(printf "x%02d.tsv" ${{ matrix.chunk }})
          echo "Processing ${INPUT_FILE}..."
          
          mkdir -p genomes_zip
          # Download all genomes for this chunk first
          cat "$INPUT_FILE" | cut -f1 | xargs -n 1 -P 8 ./datasets download genome accession --no-progressbar --filename "genomes_zip/{}.zip"
          
          echo "Unzipping all downloaded genomes..."
          mkdir -p genomes_fna
          for zipfile in genomes_zip/*.zip; do
            unzip -q -o "$zipfile" -d "unzipped_tmp"
            # Find the actual fasta file and move it to our clean directory
            find unzipped_tmp/ncbi_dataset/data -name "*.fna" -exec mv {} genomes_fna/ \;
            rm -rf unzipped_tmp
          done
          
      - name: Sketch all genomes in this chunk at once
        run: |
          export PATH=$(pwd):$PATH
          OUTPUT_SKETCH="chunk_${{ matrix.chunk }}.msh"
          echo "Sketching all genomes for this chunk..."
          ./mash sketch -k 21 -s 1000 -p 8 -o "$OUTPUT_SKETCH" genomes_fna/*.fna

      - name: Upload partial sketch artifact
        uses: actions/upload-artifact@v4
        with:
          name: partial-sketch-${{ matrix.chunk }}
          path: ${{ env.OUTPUT_SKETCH }}
          overwrite: true

  # --------------------------------------------------------------------------
  # JOB 3: Combine all partial sketches into the final database
  # --------------------------------------------------------------------------
  combine_sketches:
    # This job will run even if some of the sketching jobs failed
    if: success() || failure()
    needs: create_sketches
    runs-on: ubuntu-latest
    steps:
      - name: Download Mash
        run: |
          wget -q https://github.com/marbl/Mash/releases/download/v2.3/mash-Linux64-v2.3.tar
          tar -xvf mash-Linux64-v2.3.tar && mv mash-Linux64-v2.3/mash .
      
      - name: Download all successful sketch artifacts
        uses: actions/download-artifact@v4
        with:
          name: partial-sketch-*
          path: partial_sketches/
      
      - name: Combine all sketches
        id: paste
        run: |
          export PATH=$(pwd):$PATH
          echo "Pasting all partial sketches..."
          if [ -z "$(ls -A partial_sketches)" ]; then
            echo "No sketches were downloaded. Cannot create final database."
            exit 1
          fi
          ./mash paste Fungi_RefSeq_Database.msh $(find partial_sketches -name "*.msh")

      - name: Compress final sketch
        run: gzip Fungi_RefSeq_Database.msh

      - name: Create Release and Upload Final Sketch
        uses: softprops/action-gh-release@v2
        with:
          name: Fungal RefSeq Database ${{ github.event.inputs.refseq_version }}
          tag_name: ${{ github.event.inputs.refseq_version }}
          files: Fungi_RefSeq_Database.msh.gz
